repos:
  - repo: local
    hooks:
      - id: lint
        name: goimports
        entry: make lint
        language: system
        pass_filenames: false
      - id: test
        name: fast tests
        entry: make test
        language: system
        pass_filenames: false
